add bound fn and utf8
cesbo/textcode pull request #2
Opened 2019-12-13 11:16 UTC by maxvinza

2019-12-13 19:33 UTC, and-cesbo reviewed
Правки в комментариях

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/gb2312.rs
> +    if limit == 0 || src.len() < limit { return limit; }
тут надо проверку на <= (если limit равен len, то он влезет)

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/gb2312.rs
> +    if limit == 0 || src.len() < limit { return limit; }
и давай не в одну строку

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/gb2312.rs
> +    for byte in src.iter() {
clippy на такое будет ругаться. надо `for byte in &src {`

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/gb2312.rs
> +    for byte in src.iter() {
ещё сравнение с `<= 0x7F` - это однобайтовый (ascii-символы)
и лучше без дополнительных переменных, а циклом while, если <= 0x7F то +1, else +2

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/gb2312.rs
> +    for byte in src.iter() {
и сразу в цикле проверка, если выход за лимит, то break.

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/iso6937.rs
> +pub fn bound(_src: &[u8], limit: usize) -> usize { limit }
inline забыл

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/utf8.rs
> +    *dst = src.to_string().into_bytes();
так нельзя. в dst могут быть данные. надо `dst.extend_from_slice` использовать

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/utf8.rs
> +    *dst = String::from_utf8_lossy(src).to_string();
тут также `dst.write_str(...)`

2019-12-13 19:33 UTC, and-cesbo commented on src/charset/utf8.rs
> +    for byte in src.iter() {
тут также лучше использовать while, по первому байту можно определить, сколько байт на символ - 2, 3, или 4 (соответственно эти смиволы уже не надо будет итерировать и проверять и сразу можно будет проверить, влезет он или нет)

2019-12-15 19:05 UTC, maxvinza commented on src/charset/utf8.rs
> +    *dst = String::from_utf8_lossy(src).to_string();
использую `push_str(...)`, так как `write_str(...)` возвращает `Result<()>`

2019-12-20 18:58 UTC, and-cesbo requested changes

2019-12-20 18:58 UTC, and-cesbo commented on src/charset/gb2312.rs
> +        if let Some(byte) = src.get(cnt_limit - 1) {
тут лучше без Some - просто `src[cnt_limit - 1]`

2019-12-20 18:58 UTC, and-cesbo commented on src/charset/gb2312.rs
> +            if *byte < 0xA1 { break; }
тут получается ожидание ascii символа, а если строка без ascii , будет, то не сработает логика. может для gb2312 всё так использовать от 0 до limit ?

2019-12-20 18:58 UTC, and-cesbo commented on src/charset/gb2312.rs
> +            if *byte < 0xA1 { break; }
хотя кажется понял.

2019-12-20 18:58 UTC, and-cesbo commented on src/charset/gb2312.rs
> +    ((limit - cnt_limit) / 2) * 2 + cnt_limit
да, понял, вся фишка в этом. одобряю. только можно убрать последний бит чтобы сделать число чётным. не надо делить и умножать.

2019-12-20 18:58 UTC, and-cesbo commented on src/charset/utf8.rs
> +            } else if *byte >= 0xF0 {
тут лучше по битовой маске проверять. начиная с 2-х байтовых
т.е. сначала правильно if <= 0x7F
потом if (byte & 0xE0) == 0xC0 - два байта
потом if (byte & 0xF0) == 0xE0 - три байта
потом if (byte & 0xF8) == 0xF0 - четыре байта

ну и также как в верху без get() сразу байт брать из src[cnt_limit]

2019-12-22 18:12 UTC, and-cesbo reviewed
Мысль ещё, может функцию bound переименовать в slice - по аналогии с js. хотя с другой стороны не совсем slice...

2019-12-22 18:12 UTC, and-cesbo commented on src/charset/utf8.rs
> +            } else if *byte >= 0xF0 {
можно сделать одним сравнением

if byte <= 0x7F - ascii
else if byte <= 0xBF - не первый байт утф8 и просто continue
else break

2019-12-23 08:48 UTC, maxvinza commented on src/charset/utf8.rs
> +            } else if *byte >= 0xF0 {
Поправил

2019-12-23 09:13 UTC, and-cesbo approved these changes

2019-12-23 09:13 UTC, merged